## Adapted from Libero sample configuration.
## https://github.com/libero/sample-configuration/blob/master/.travis.yml
sudo: required

language: minimal

services: docker

before_install:
  - docker -v

install:
  - travis_retry docker build . -t digirati/madoc-omeka-s

cache:
  bundler: true
  directories:
    - $HOME/docker

deploy:
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-omeka-s
    on:
      branch: master

if: |
  branch = master OR \
  type = pull_request
